- name: Install nginx
  ansible.builtin.yum:
    name: nginx
    state: installed

- name: Include common role
  ansible.builtin.include_role:
    name: common
    tasks_from: download

- name: Update the systemd service
  ansible.builtin.template:
    src: roboshop.conf
    dest: /etc/nginx/default.d/roboshop.conf

- name: Update the nginx service
  ansible.builtin.template:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf

- name: Restart the {{COMPONENT}} service
  ansible.builtin.systemd:
    name: nginx
    state: restarted
    enabled: yes

- name: Copy Filebeat configuration
  ansible.builtin.include_role:
    name: elk
    tasks_from: filebeat



