- name: Configure the logstash template
  ansible.builtin.template:
    src: logstash.conf
    dest: /etc/logstash/conf.d/logstash.conf

- name: restart rsyslog
  ansible.builtin.systemd:
    name: logstash
    state: restarted

- name: Check logstash is running or not
  ansible.builtin.wait_for:
    host: 0.0.0.0
    port: 5044
    delay: 10
    timeout: 30