- name: Setup RSYSLOG config
  ansible.builtin.include_role:
    name: elk
    tasks_from: rsyslog
  when: SETUP_TYPE == "rsyslog"

- name: Setup LOGSTASH config
  ansible.builtin.include_role:
    name: elk
    tasks_from: logstash
  when: SETUP_TYPE == "logstash"

