- name: Configure the rsyslog template
  ansible.builtin.template:
    src: rsyslog.conf
    dest: /etc/rsyslog.d/rsyslog.conf

- name: restart rsyslog
  ansible.builtin.systemd:
    name: rsyslog
    state: restarted