- name: prometheus server setup
  ansible.builtin.include_role:
    name: prometheus
    tasks_form: server
  when: SETUP_TYPE == "server"

- name: Prometheus client setup
  ansible.builtin.include_role:
    name: prometheus
    tasks_form: client
  when: SETUP_TYPE == "client"

