- name: Prometheus server configuration
  ansible.builtin.template:
    src: prometheus.yml
    dest: /opt/prometheus/prometheus.yml

- name: Prometheus alert setup configuration
  ansible.builtin.template:
    src: alerts.yml
    dest: /opt/prometheus/alerts.yml

- name: Restart prometheus server
  ansible.builtin.systemd:
    name: prometheus
    state: restarted

- name: Check for prometheus service is running or not
  ansible.builtin.wait_for:
    host: 0.0.0.0
    port: 9090
    delay: 10
    timeout: 15

- name: Prometheus alert manager setup configuration
  ansible.builtin.template:
    src: alertmanager.yml
    dest: /opt/alertmanager/alertmanager.yml
    
- name: Restart alertmanager server
  ansible.builtin.systemd:
    name: alertmanager
    state: restarted

- name: Check for alertmanager service is running or not
  ansible.builtin.wait_for:
    host: 0.0.0.0
    port: 9093
    delay: 10
    timeout: 15



