- name: Prometheus setup configuration
  ansible.builtin.template:
    src: prometheus.yml
    dest: /opt/prometheus/prometheus.yml

- name: Restart prometheus server
  ansible.builtin.systemd:
    name: prometheus
    state: restarted