- name: Add the application user
  ansible.builtin.user:
    name: roboshop
  register: app_user

- name: remove app location
  ansible.builtin.file:
    path: "{{APP_LOCATION}}"
    state: absent

- name: add app location
  ansible.builtin.file:
    path: "{{APP_LOCATION}}"
    state: directory

#- name: Download and Extract the {{COMPONENT}} content
#  ansible.builtin.unarchive:
#    src: https://github.com/roboshop-devops-project/{{COMPONENT}}/archive/main.zip
#    dest: /tmp
#    remote_src: yes
#
#- name: Copy file to app location
#  ansible.builtin.copy:
#    src: /tmp/{{COMPONENT}}-main/{{SUFFIX}}
#    dest: "{{APP_LOCATION}}/"
#    remote_src: yes

- name: Download and Extract the {{COMPONENT}} content to nexus
  ansible.builtin.unarchive:
    src: http://nexus.roboshop.internal:8081/repository/{{COMPONENT}}/{{COMPONENT}}-{{APP_VERSION}}.zip
    dest: "{{APP_LOCATION}}"
    remote_src: yes