- name: Create set host name
  ansible.builtin.shell: set-hostname {{COMPONENT}}

- name: Install pip3 dependencies
  ansible.builtin.pip:
    name:
      - botocore
      - boto3
    executable: pip3
