- name: Download yum repos
  ansible.builtin.shell: curl --silent --location https://rpm.nodesource.com/setup_16.x | sudo bash -

- name: Install nodejs
  ansible.builtin.yum:
    name: nodejs
    state: installed

- name: Include common role
  ansible.builtin.include_role:
    name: common
    tasks_from: download

- name: Install nodejs dependencies
  community.general.npm:
    path: "{{APP_LOCATION}}"

- name: Download DOCDB pem file
  ansible.builtin.get_url:
    url: https://s3.amazonaws.com/rds-downloads/rds-combined-ca-bundle.pem
    dest: /home/roboshop/catalogue/rds-combined-ca-bundle.pem
    mode: "0400"
    owner: roboshop
    group: roboshop
  when: DOCDB_ENDPOINT != "null"

- name: Include systemd service
  ansible.builtin.include_role:
    name: common
    tasks_from: systemd

- name: Copy Filebeat configuration
  ansible.builtin.include_role:
    name: elk
    tasks_from: filebeat