global:
  scrape_interval: 15s
  evaluation_interval: 15s

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

rule_files:
scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["172.31.90.83:9100"]
